version: '3'
services:
  "web-application":
    build: "./web-application"
    ports:
      - "3000:8080"
      - "9229:9229"
    volumes:
      - "./web-application/src:/web-application/src"
    depends_on:
      - database
      - redis
  database:
    build: ./database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=theRootPassword
      - MYSQL_DATABASE=webAppDatabase
  # database-postgres:
  #   image: postgres
  #   environment: 
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: postgres_db
  #   volumes: 
  #     - ./database-postgres
  #   ports:
  #     - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"